from aetypes import Enum

__author__ = 'cenk'

DISSIMILARITY_ABBR = 0
DISTANCE_ABBR = 1
SIMILARITY_RATIO_ABBR = 2
DISSIMILARITY_RATIO_ABBR = 3

DISSIMILARITY = "dissimilarity"
DISTANCE = "distance"
SIMILARITY_RATIO = "similarity_ratio"
DISSIMILARITY_RATIO = "dissimilarity_ratio"


class DistanceType(Enum):
    DISSIMILARITY = DISSIMILARITY_ABBR
    DISTANCE = DISTANCE_ABBR
    SIMILARITY_RATIO = SIMILARITY_RATIO_ABBR
    DISSIMILARITY_RATIO = DISSIMILARITY_RATIO_ABBR