from enum import Enum

__author__ = 'cenk'

DISSIMILARITY_ABBR = 0
DISTANCE_ABBR = 1
SIMILARITY_RATIO_ABBR = 2
DISSIMILARITY_RATIO_ABBR = 3
DISTANCE_RATIO_ABBR = 4
DISSIMILARITY = "dissimilarity"
DISTANCE = "distance"
SIMILARITY_RATIO = "similarity_ratio"
DISTANCE_RATIO = "distance_ratio"
DISSIMILARITY_RATIO = "dissimilarity_ratio"


class SimilarityMeasureType(Enum):
    DISSIMILARITY_ABBR = DISSIMILARITY
    DISTANCE_ABBR = DISTANCE
    SIMILARITY_RATIO_ABBR = SIMILARITY_RATIO
    DISSIMILARITY_RATIO_ABB = DISSIMILARITY_RATIO
    DISTANCE_RATIO_ABBR = DISTANCE_RATIO